### PR TITLE
Added comment Date modified - I think it will be useful to determine …

### PR DESCRIPTION
**Pull request by pk6au**
1 - Added comment Date modified - I think it will be useful to determine version of file.
2 - Added performance metrics from v$sysmetrics.
3 - Added performance metrics from v$eventmetric in AWR style
4 - Change explanation for previous commit for performance issue with dba_free_space.
============/
I think that `user calls` metric from old `sysstat:` and new `sysmetric:`  is the same. But I did not check yet.

### CODE REVIEW

**Comment by ikzelf** [comment]
One thing to be aware of, is the view safe, or does it need additional licenses for statspack or tuningpack. I don’t want to cause unexpected usage of those licenses.
Did you check this?

**Comment by pk6au** [comment]
Hi, Ronald.
I will change views to GV$ views.
Could you help me to find way to determine do v$sysmetrics v$eventmetric require any additional licenses or not?

**Comment by ikzelf** [comment]
As far as I can see here https://docs.oracle.com/en/database/oracle/oracle-database/18/dblic/Licensing-Information.html#GUID-75262092-CD86-4B30-A21B-92ECC1C2E130
it looks like safe.

**Comment by ikzelf** [comment]
thanks, I merged your changes.

**Pull request merged**
